# This is a basic workflow to help you get started with Actions

name: Android Build CI

# Controls when the workflow will run
on: [workflow_dispatch, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        flag: [ONLY_ARMV7, ONLY_ARM64]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - name: Setup Android NDK r21e
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: Setup JDK 17 Temurin
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
      - name: Setup gradle.properties
        uses: SimonMarquis/ci-gradle-properties-action@v1
        with:
           path: .github/gradle.properties
      - name: Setup build.gradle
        uses: thecodemonkey/action-get-gradle-version@v1.0
        with:
          file: .github/build.gradle
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-addons 2.10.0
          haxelib install flixel-ui 2.3.3
          haxelib install hscript
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git f3c0320aa51c848318934c2893ed78f42b7de74c
          haxelib git extension-webm https://github.com/a-random441/extension-webm.git
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git c0f09f2399780091de02eb40caf5ac4f695f9cac
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib install actuate 
          haxelib list
          
      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: build logs lol (${{matrix.flag}})
        run: haxelib run lime build android -D ${{matrix.flag}}
          
      - uses: actions/upload-artifact@v4
        with:
          name: androidBuild-${{matrix.flag}}
          path: export/release/android/bin/app/build/outputs/apk/debug
